[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Resource-Policy = "cross-origin"
    Content-Security-Policy = "default-src 'self' https://logo.clearbit.com https://miro.medium.com; img-src 'self' https://logo.clearbit.com https://miro.medium.com data:; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com; script-src 'self' https://*.firebasejs.com; style-src 'self' 'unsafe-inline'; frame-src 'self' https://*.firebaseapp.com"